[package]
authors = ["Walther Chen <walther.chen@gmail.com>", "Daniel Brotsky <dev@brotsky.com>"]
description = "Cross-platform library for managing passwords/credentials"
homepage = "https://github.com/hwchen/keyring-rs"
keywords = ["password", "credential", "keychain", "keyring", "cross-platform"]
license = "MIT OR Apache-2.0"
name = "keyring"
repository = "https://github.com/hwchen/keyring-rs.git"
version = "1.2.1"
edition = "2018"
exclude = [".github/"]

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.6.1"

[target.'cfg(target_os = "ios")'.dependencies]
security-framework = "2.6.1"

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "2.0.1"

[target.'cfg(target_os = "android")'.dependencies]
secret-service = "2.0.1"

[target.'cfg(target_os = "windows")'.dependencies]
byteorder = "1.2.1"
winapi = { version =  "0.3", features = ["wincred", "winerror", "errhandlingapi", "minwindef"] }

[[example]]
name = "ios"
path = "examples/ios.rs"
crate-type = ["staticlib"]

[dev-dependencies]
clap = { version = "3", features = ["derive", "wrap_help"] }
rpassword = "5.0"
rand = "0.8.4"
doc-comment = "0.3.3"
whoami = "1.2.0"
